[tool.poetry]
name = "miexp"
version = "0.1.0"
description = ""
authors = ["Henry Scheible <henry.scheible@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
torch = "2.5.1"
numpy = "^2.1.3"
ipykernel = "^6.29.5"
scikit-learn = "^1.5.2"
tqdm = "^4.67.0"
iprogress = "^0.4"
ipywidgets = "^8.1.5"
jupyter = "^1.1.1"
plotly = "^5.24.1"
pandas = "^2.2.3"

[tool.poetry.group.dev.dependencies]
pyright = "^1.1.388"
pytest = "^8.3.3"
ruff = "^0.7.3"
black = "^24.10.0"
ipython = "^8.29.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
