[tool.poetry]
name = "miexp"
version = "0.1.0"
description = ""
authors = ["Henry Scheible <henry.scheible@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
torch = "2.5.1"

[tool.poetry.group.dev.dependencies]
pyright = "^1.1.388"
pytest = "^8.3.3"
ruff = "^0.7.3"
black = "^24.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
