name: Check Experiments

on: [push]

jobs:
  check-experiment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'true'
      - run: git lfs pull

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Check Majority Training
        run: cd experiments/majority_training && make train_dry_run

      - name: Check Double Majority Training
        run: cd experiments/double_majority_training && make train_dry_run

      - name: Check Fourier Training
        run: cd experiments/fourier_training && make train_dry_run

      - name: Check Bulk Fourier Training
        run: cd experiments/fourier_training && mkdir results_dry_run && make bulk_train_dry_run
      
      - name: Check Fourier Training Streamlit
        run: cd apps/fourier_transformer_viewer && make check_streamlit