name: Tests

on: [push]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Lint
        run: uvx ruff check

      - name: Check Format
        run: uvx ruff format --check

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run Static Type Checking
        run: uv run pyright

      - name: Run tests
        run: uv run pytest --cov-report term --cov src